// Writes a golden backup fixture using WHATEVER VERSION OF THE APP IT IS RUN INSIDE (006 T028).
//
// This file is never run by `npm test`. `scripts/make-backup-fixture.mjs` checks out a historical
// commit into a git worktree, drops this file into it, and runs jest there - so the bytes that come
// out were produced by the app exactly as it stood on the day that schema version was current.
//
// That detour is the entire point. A fixture generated by TODAY's code and labelled "version 1"
// proves nothing: it proves today's writer agrees with today's reader, which was never in doubt. The
// question T028 asks is whether a file written a year ago still opens, and only a file actually
// written by that code can answer it.
//
// It lives in `scripts/` rather than `__tests__/` because it is a tool, not a test - jest is simply
// the only TypeScript runner this repo has. `jest.config.js` excludes this directory from the normal
// run for that reason.
//
// WHEN THE SCHEMA MOVES AGAIN: leave this file alone if the new version's `BackupSource` still
// accepts the data below, and add the new fixture by pointing the script at the right commit. If the
// source interface changed, the version of this file living in the OLD worktree is the one that
// matters - git has it - so amend here freely for the new shape.

import { writeFileSync } from 'fs';
import { buildPayload, encodePayload } from '../../src/services/backup/snapshot';
import { seal } from '../../src/services/backup/envelope';
import { format } from '../../src/services/backup/recoveryKey';

/**
 * The key the fixture is sealed under, and it is in the repository on purpose.
 *
 * It protects nothing: everything inside the fixture is invented, and a golden test that cannot open
 * its own golden file is not a test. Spelled so it cannot be mistaken for somebody's real key if it
 * ever turns up in a log - `TEST 0N1Y F1XTVRE KEY`.
 *
 * WRITTEN UNGROUPED, and rebuilt with the app's own `format`, because the secret scanner has a rule
 * for a grouped recovery key (`.trivy-secret.yaml`) and it is right to have one. The alternative was
 * three entries in `.trivyignore.yaml` exempting the files most likely to acquire a real key by
 * accident later. One call is cheaper than a permanent hole, and it goes through the same function
 * the app uses to render a key, so the fixture is sealed under exactly the string a phone would use.
 */
const FIXTURE_KEY = format('TEST0N1YF1XTVREKEY00');

/**
 * Deliberately far below `KDF_DEFAULTS`.
 *
 * The golden test opens this file on every single run, and Argon2id at 64 MiB in pure JavaScript
 * costs about a second of it. The parameters travel INSIDE the envelope - that is the whole reason
 * they are written into the header - so a file made at 8 MiB opens with 8 MiB while today's backups
 * are still written at 64. Which means this shortcut is not only free, it exercises a property the
 * defaults never would: that an old file's own costs are honoured rather than assumed.
 */
const FIXTURE_KDF = { m: 8192, t: 1, p: 1 };

/**
 * Invented mail, and it has to stay invented (Constitution III, VII).
 *
 * A fixture is committed, public, and forever. The rows below are shaped like real ones and are
 * about nothing - two boxes that do not exist, four messages nobody sent. What they DO carry is one
 * of each case the restore has to get right: a message with a downloaded body and one without, a
 * draft, a reminder, and a setting that must not travel between phones.
 */
const ACCOUNTS = [
  {
    boxId: 'fx2test',
    loginName: 'fixture.second',
    label: 'Fiktivní s.r.o.',
    alias: null,
    dbType: 'PO',
    authMethod: 'password',
    host: 'ws1.mojedatovaschranka.cz',
    passwordExpiresAt: 1_800_000_000_000,
    createdAt: 1_700_000_000_000,
  },
  {
    boxId: 'fx1test',
    loginName: 'fixture.first',
    label: 'Zkušební schránka',
    alias: 'Doma',
    dbType: 'FO',
    authMethod: 'otp',
    host: 'ws1.czebox.cz',
    passwordExpiresAt: null,
    createdAt: 1_690_000_000_000,
  },
];

const ENVELOPES: Record<string, Record<string, unknown[]>> = {
  fx1test: {
    received: [
      {
        boxId: 'fx1test',
        messageId: '1000001',
        folder: 'received',
        subject: 'Rozhodnutí ve věci vymyšlené',
        sender: 'Úřad, který neexistuje',
        senderAddress: 'Nikde 1, 000 00 Nikde',
        recipient: 'Zkušební schránka',
        recipientAddress: 'Nikde 1, 000 00 Nikde',
        deliveryTime: 1_710_000_000_000,
        acceptanceTime: 1_710_086_400_000,
        state: 5,
        attachmentSize: 12_345,
        detailJson: null,
        downloadedAt: null,
      },
      {
        boxId: 'fx1test',
        messageId: '1000002',
        folder: 'received',
        subject: 'Bez staženého obsahu',
        sender: 'Úřad, který neexistuje',
        senderAddress: null,
        recipient: 'Zkušební schránka',
        recipientAddress: null,
        deliveryTime: 1_712_000_000_000,
        acceptanceTime: null,
        state: 4,
        attachmentSize: null,
        detailJson: null,
        downloadedAt: null,
      },
    ],
    sent: [
      {
        boxId: 'fx1test',
        messageId: '1000003',
        folder: 'sent',
        subject: 'Odpověď',
        sender: 'Zkušební schránka',
        senderAddress: null,
        recipient: 'Úřad, který neexistuje',
        recipientAddress: null,
        deliveryTime: 1_713_000_000_000,
        acceptanceTime: 1_713_000_000_000,
        state: 6,
        attachmentSize: 900,
        detailJson: null,
        downloadedAt: null,
      },
    ],
  },
  fx2test: {
    received: [
      {
        boxId: 'fx2test',
        messageId: '2000001',
        folder: 'received',
        subject: 'Druhá schránka',
        sender: 'Jiný neexistující úřad',
        senderAddress: null,
        recipient: 'Fiktivní s.r.o.',
        recipientAddress: null,
        deliveryTime: 1_714_000_000_000,
        acceptanceTime: null,
        state: 4,
        attachmentSize: 4_096,
        detailJson: null,
        downloadedAt: null,
      },
    ],
    sent: [],
  },
};

/** Only 1000001 was ever opened, so only it has a body. */
const DETAILS: Record<string, string> = {
  '1000001': JSON.stringify({
    documents: [{ fileName: 'rozhodnuti.pdf', mimeType: 'application/pdf' }],
  }),
};

describe('golden backup fixture', () => {
  it('writes one', async () => {
    const out = process.env.FIXTURE_OUT;
    if (!out) {
      throw new Error('FIXTURE_OUT must point at the file to write.');
    }
    const payload = await buildPayload({
      listAccounts: async () => ACCOUNTS as never,
      listEnvelopes: async (boxId: string, folder: string) =>
        JSON.parse(
          JSON.stringify(ENVELOPES[boxId]?.[folder] ?? []),
        ) as never,
      messageDetail: async (_boxId: string, messageId: string) =>
        DETAILS[messageId] ?? null,
      listDrafts: async (boxId: string) =>
        boxId === 'fx1test'
          ? ([
              {
                id: 'draft-1',
                boxId: 'fx1test',
                recipientBoxId: 'fx2test',
                recipientName: 'Fiktivní s.r.o.',
                recipientAddress: null,
                subject: 'Rozepsané',
                body: 'Dobrý den,',
                updatedAt: 1_715_000_000_000,
              },
            ] as never)
          : ([] as never),
      listReminders: async (boxId: string) =>
        boxId === 'fx1test'
          ? ([
              {
                boxId: 'fx1test',
                messageId: '1000001',
                date: 1_720_000_000_000,
                createdBy: 'user',
                createdAt: 1_710_100_000_000,
              },
            ] as never)
          : ([] as never),
      // `activeBoxId` is device-local and the snapshot is supposed to drop it. Included here so the
      // golden test can assert that it is absent rather than take the writer's word for it.
      allSettings: async () => ({
        activeBoxId: 'fx1test',
        theme: 'system',
        locale: 'cs',
      }),
    });

    const sealed = await seal(
      await encodePayload(payload),
      FIXTURE_KEY,
      FIXTURE_KDF,
    );
    writeFileSync(out, Buffer.from(sealed));
    console.log(
      `wrote ${sealed.length} bytes to ${out} (schemaVersion ${payload.schemaVersion})`,
    );
  });
});
