// A secret never reaches persistent storage or a log (001 SC-006, T044).
//
// This app holds two kinds of credential - a data-box password and, since 018, a session cookie that
// is a bearer token for that box - for mail with legal deadlines attached. The architecture that
// keeps them safe is not one mechanism but four: passwords and session cookies are sealed in the
// Keychain and the DB holds only a pointer; the SQLCipher key is generated by a CSPRNG and stored in the secure enclave; the logger
// redacts; nothing writes to the console at all.
//
// None of that was pinned by a test. Every part of it is the kind of thing a well-meaning change
// quietly undoes - a column added "for convenience", a debug log left behind, a fallback key so the
// DB opens in a simulator. So the assertions here are deliberately blunt: take a password nobody
// would type by accident, push it through the real code, and go looking for it everywhere it could
// have leaked.

// Node's own types are referenced here rather than added to tsconfig's global `types`: this suite
// reads source files off disk, and pulling @types/node in app-wide would swap RN's timer/Buffer
// globals underneath every other file to fix one test.
/// <reference types="node" />
import { readFileSync, readdirSync, statSync } from 'fs';
import { join } from 'path';
import { AccountsController } from '../../src/features/accounts/state/accountsController';
import { InMemoryAccountsStore } from '../../src/services/db/accountsStore';
import { InMemorySecureStore } from '../../src/services/secureStore/secureStore';
import { redact } from '../../src/services/logging/logger';
import { encodeUtf8 } from '../../src/services/text/textCodec';
import { buildPayload } from '../../src/services/backup/snapshot';
import { seal } from '../../src/services/backup/envelope';
import type { OwnerInfo } from '../../src/services/isds/types';

/** Distinctive enough that finding it anywhere is unambiguous. */
const PASSWORD = 'SENTINEL-pa55word-must-never-persist';
const COOKIE = 'IPCZ-X-COOKIE=SENTINEL-session-token';

const ownerInfo: OwnerInfo = {
  boxId: 'abc123',
  label: 'Jan Novák',
  dbType: 'FO',
  passwordExpiresAt: null,
};

async function addBox() {
  const accounts = new InMemoryAccountsStore();
  const secureStore = new InMemorySecureStore();
  const controller = new AccountsController({
    accounts,
    secureStore,
  });
  await controller.addAccount({
    loginName: 'novakjan',
    password: PASSWORD,
    method: 'otp_totp',
    host: 'production',
    ownerInfo,
    sessionCookie: COOKIE,
  });
  return { accounts, secureStore, controller };
}

describe('the password never reaches the database', () => {
  it('persists a pointer to the secret, not the secret', async () => {
    const { accounts } = await addBox();
    const rows = await accounts.list();
    // Every value of every row, exactly as it would be written to SQLite.
    expect(JSON.stringify(rows)).not.toContain(PASSWORD);
    expect(rows[0].secretRef).toBeTruthy();
    expect(rows[0].secretRef).not.toContain(PASSWORD);
  });

  it('puts it in the secure store, and only there', async () => {
    const { secureStore } = await addBox();
    expect(await secureStore.readPassword('abc123')).toEqual({ status: 'found', value: PASSWORD });
  });

  it('does not leak it through the settings table either', async () => {
    // app_settings is a loose key/value bag - the easiest place for something to be stashed.
    const { accounts } = await addBox();
    const settings = await Promise.all(
      ['themeMode', 'locale', 'appLock', 'scanAttachments', 'activeBoxId'].map(k =>
        accounts.getSetting(k),
      ),
    );
    expect(JSON.stringify(settings)).not.toContain(PASSWORD);
  });

  it('takes the secret with the box when it is removed', async () => {
    const { accounts, secureStore, controller } = await addBox();
    await controller.removeAccount('abc123');
    expect(await secureStore.readPassword('abc123')).toEqual({ status: 'absent' });
    expect(await accounts.list()).toEqual([]);
  });
});

describe('the session cookie - stored, and not in the database any more', () => {
  it('is kept in the secure store beside the password, never in the accounts row', async () => {
    // 018: a cookie session is per box and has to survive a restart, or every OTP box would ask for
    // an SMS code on every launch. 018 kept it in the SQLCipher database, whose key is readable
    // whenever the phone is unlocked - so with the app lock on, the session stayed readable behind
    // the lock. Since 001 T028 it is sealed under the vault key like the password.
    const { accounts, secureStore } = await addBox();
    expect(await secureStore.readSession('abc123')).toEqual({ status: 'found', value: COOKIE });
    const rows = await accounts.list();
    expect(JSON.stringify(rows)).not.toContain(COOKIE);
    expect('sessionCookie' in rows[0]).toBe(false);
  });

  it('is never written to the accounts table again - the old column is only ever emptied', () => {
    // The column stays in the schema (a shipped migration is not edited). What must not come back
    // is a write of a VALUE into it: an insert naming it, or an update setting it from a parameter.
    const source = readFileSync('src/services/db/sqliteAccountsStore.ts', 'utf8');
    const insertColumns = /INSERT INTO accounts\s*\(([^)]*)\)/.exec(source)?.[1] ?? '';
    expect(insertColumns).toContain('boxId');
    expect(insertColumns).not.toContain('sessionCookie');
    expect(source).not.toMatch(/sessionCookie\s*=\s*\?/);
    expect(source).toMatch(/SET sessionCookie = NULL/);
  });

  it('does not outlive the box it belonged to (018 FR-004)', async () => {
    const { accounts, secureStore, controller } = await addBox();
    await controller.removeAccount('abc123');
    expect(await secureStore.readSession('abc123')).toEqual({ status: 'absent' });
    expect(JSON.stringify(await accounts.list())).not.toContain(COOKIE);
  });
});

describe('redaction covers the shapes this app actually logs', () => {
  it('strips both credentials out of a real transport call', () => {
    // The exact object shape `IsdsHttpTransport` receives. The generic logger tests use invented
    // keys; this one uses the ones that would actually be in front of a `logger.debug`.
    const args = {
      host: 'production',
      authMethod: 'otp_totp',
      loginName: 'novakjan',
      password: PASSWORD,
      sessionCookie: COOKIE,
      headers: { Authorization: 'Basic bm92YWtqYW46c2VjcmV0' },
    };
    const safe = JSON.stringify(redact(args));
    expect(safe).not.toContain(PASSWORD);
    expect(safe).not.toContain(COOKIE);
    expect(safe).not.toContain('Basic bm92YWtqYW4');
    // The login name stays: it is not a secret, and a log with no identity in it is useless.
    expect(safe).toContain('novakjan');
  });

  it('strips a one-time code, which is a credential for as long as it lives', () => {
    const safe = JSON.stringify(redact({ code: '35124603', otp: '35124603' }));
    expect(safe).not.toContain('35124603');
  });
});

/** Every TypeScript source file the app ships, excluding generated data. */
function appSources(dir = 'src'): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) {
      out.push(...appSources(path));
    } else if (/\.tsx?$/.test(entry) && !entry.endsWith('.generated.ts')) {
      out.push(path);
    }
  }
  return out;
}

describe('nothing shipped writes to the console', () => {
  // Not style policing. A stray `console.log(args)` during debugging is the single most likely way a
  // password or session cookie ends up in a device log - and it survives review easily, because it
  // does nothing visible. Two such lines were written (and removed) during 010's scan work alone.
  //
  // `logger.ts` is the one deliberate exception: its sink reaches the console through computed access
  // and only ever receives metadata that `redact()` has already been through.
  it('has no direct console calls in src/', () => {
    const offenders = appSources()
      .filter(f => !f.endsWith('services/logging/logger.ts'))
      .flatMap(file => {
        const lines = readFileSync(file, 'utf8').split('\n');
        return lines
          .map((line, i) => ({ file, line: i + 1, text: line }))
          .filter(l => /(^|[^.\w])console\s*\.\s*\w+\s*\(/.test(l.text));
      })
      .map(l => `${l.file}:${l.line}  ${l.text.trim().slice(0, 80)}`);
    expect(offenders).toEqual([]);
  });
});

describe('a backup is a new place for a secret to leak (006)', () => {
  // A snapshot is written to a file and handed to iCloud or Google Drive. Everything this suite
  // guards about the DATABASE has to hold there too, and it is a fresh chance to get it wrong:
  // one `{...account}` spread would carry the session cookie into somebody else's cloud.
  const backupAccount = {
    boxId: 'abc123',
    loginName: 'novakjan',
    label: 'Jan Novák',
    alias: null,
    dbType: 'FO',
    authMethod: 'otp_totp',
    host: 'production',
    passwordExpiresAt: null,
    createdAt: 1,
    // The fields a snapshot must refuse to copy, present on the source row exactly as they are in
    // the real accounts table.
    sessionCookie: COOKIE,
    secretRef: 'ref-abc123',
    password: PASSWORD,
  };

  it('carries neither the password nor the session cookie out of the device', async () => {
    const payload = await buildPayload({
      listAccounts: async () => [backupAccount as never],
      listEnvelopes: async () => [],
      messageDetail: async () => null,
      listDrafts: async () => [],
      listReminders: async () => [],
      allSettings: async () => ({}),
    });
    const asText = JSON.stringify(payload);
    expect(asText).not.toContain(PASSWORD);
    expect(asText).not.toContain(COOKIE);
    expect(asText).not.toContain('secretRef');
    // …while still being a usable backup of the box.
    expect(payload.accounts[0]).toMatchObject({ boxId: 'abc123', loginName: 'novakjan' });
  });

  it('keeps them out of the sealed bytes as well', async () => {
    // The plaintext check above is the one that matters, but the encrypted artefact is what actually
    // leaves the phone - so look there too, in case a future version adds an unencrypted header.
    const sealed = await seal(
      encodeUtf8(JSON.stringify({ accounts: [{ boxId: 'abc123' }] })),
      'FKPX-9WQ2-7TDM-4RJH-2CVB',
      { m: 256, t: 1, p: 1 },
    );
    const asText = Buffer.from(sealed).toString('utf8');
    expect(asText).not.toContain(PASSWORD);
    expect(asText).not.toContain(COOKIE);
  });
});

describe('the database key is generated, never written down', () => {
  const source = readFileSync('src/services/db/database.ts', 'utf8');

  it('comes from a CSPRNG and the platform keychain', () => {
    expect(source).toMatch(/getRandomValues/);
    expect(source).toMatch(/Keychain\.(get|set)GenericPassword/);
  });

  it('has no hardcoded key to fall back to', () => {
    // A literal long enough to be a key, or an obvious dev fallback, must never appear here - a DB
    // that opens without the enclave is a DB anyone can read.
    const literals = [...source.matchAll(/['"`]([A-Za-z0-9+/=]{24,})['"`]/g)].map(m => m[1]);
    expect(literals).toEqual([]);
    expect(source).not.toMatch(/encryptionKey\s*[:=]\s*['"`]/);
  });

  it('binds the key to this device and to an unlocked state', () => {
    expect(source).toMatch(/WHEN_UNLOCKED_THIS_DEVICE_ONLY/);
  });
});
